Repository ConnectingStar/ConnectingStar-Front, pull requests merged in 2024-07, with the labels that each got.

#110 [TS-360] 해금 모달 별 로티 애니메이션 추가
  src/components/StarPage/Modal/CharacterUnlockModal.tsx
Labels: enhancement

#115 [TS-364] Refactor: footer btn text color refactoring
  src/components/common/FooterBtn/FooterBtn.Style.ts
Labels: Refactor

#117 [TS-366] 해금 모달 페이드인 추가
  src/components/StarPage/Modal/CharacterUnlockModal.tsx
Labels: enhancement

#118 [TS-367] Clarity 스크립트 코드 추가
  index.html
Labels: enhancement

#122 [TS-372] Refactor user identity text exception
  src/components/Habit/Profile/Profile.tsx
  src/pages/MyInfoPage/MyInfoPage.tsx
Labels: Refactor

#125 [TS-374] SelectTagModal에 글자수 10자 제한 추가
  src/components/common/Modal/CommonModal/SelectTagModal/SelectTagModal.tsx
Labels: enhancement

#128 [TS-380] chatData 메시지 수정
  src/constants/chatData.tsx
Labels: Refactor

#132 [TS-381] 체크박스가 있는 바텀시트 터치 영역 확장
  src/components/MyPage/Modal/SortModal.tsx
  src/components/common/Modal/CommonModal/SelectAgeRangeModal.tsx
  src/components/common/Modal/CommonModal/SelectGenderModal/SelectGenderModal.style.ts
  src/components/common/Modal/CommonModal/SelectGenderModal/SelectGenderModal.tsx
Labels: enhancement

#134 [TS-386] 바텀시트 체크박스 아이콘 안보이는 버그 픽스
  src/components/common/Modal/CommonModal/SelectGenderModal/SelectGenderModal.style.ts
Labels: bug
